# docker-compose up --build &
# git add . && git add * && git commit -m "update docker compose" && git push
version: '3'
services:
  backend:
    hostname: backend
    build:
      context: ./backend
      dockerfile: Dockerfile
    networks:
      - api_network
    ports:
      - "5000:5000"
  frontend:
    hostname: frontend
    environment:
      - api_key=key_test
      - another_key="3306"
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "4000:80"
    networks:
      - api_network
networks:
  api_network:
    driver: bridge
