# docker-compose up --build &
# git add . && git add * && git commit -m "update docker compose" && git push
# git fetch --all;git reset --hard origin/main;
version: '3'
services:
  backend:
    container_name: backend
    hostname: backend
    build:
      context: ./backend
      dockerfile: Dockerfile
    networks:
      - api_network
    ports:
      - "5600:5600"
  frontend:
    container_name: frontend
    hostname: frontend
    environment:
      - api_key=key_test
      - another_key="3306"
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "4500:80"
    networks:
      - api_network
  nginx:
    restart: always    
    container_name: nginx
    hostname: nginx
    build:
      context: ./nginx
      dockerfile: Dockerfile
    volumes:
      #- "./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro"
      - "./nginx/nginx.conf:/etc/nginx/nginx.conf:ro"
      - "./nginx/mime.types:/etc/nginx/mime.types:ro"
      - "./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro"
    volumes_from:
      - frontend
      - backend
    ports:
      - "8080:80"
    networks:
      - api_network
networks:
  api_network:
    driver: bridge
