# docker-compose up --build &
version: '3'
services:
  backend:
    hostname: backend
    build:
      context: ./backend
      dockerfile: Dockerfile
    networks:
      - api_network
    ports:
      - "5000:5000"
  frontend:
    hostname: frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "4000:80"
    networks:
      - api_network
networks:
  api_network:
    driver: bridge
